INSERT INTO BUILDING(ID, NAME) VALUES(-1, 'Building-1');
INSERT INTO BUILDING(ID, NAME) VALUES(-2, 'Building-2');

INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-100, 'Room-1', 1, -1);
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-101, 'Room-2', 1, -1);
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-102, 'Room-3', 2, -2);
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-103, 'Room-4', 2, -2);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1001, 20, 'ON', -100);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1002, 34, 'OFF', -100);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1003, 44, 'OFF', -100);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1004, 12, 'OFF', -101);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1005, 08, 'OFF', -101);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1006, 80, 'OFF', -102);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1007, 41, 'OFF', -102);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1008, 42, 'OFF', -103);