INSERT INTO BUILDING(ID, NAME) VALUES(-100, 'B1');
INSERT INTO BUILDING(ID, NAME) VALUES(-101, 'B2');

INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-10, 'Room1', 1, -100);
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-9, 'Room2', 1, -101);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1, 8, 'ON', -9);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-2, 0, 'OFF', -10);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-3, 0, 'OFF', -9);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-4, 0, 'OFF', -10);